import { ICONS } from "./icons";

export type MarkerKind =
  | "line"
  | "dot"
  | "disc"
  | "ring"
  | "cross"
  | "diamond"
  | "square"
  | "triangle";

export interface LayerDef {
  readonly id: string;
  readonly z: number;
  label: string;
  group: "data" | "upcoming";
  /** Chip icon color. */
  accent: string;
  /** Active chip background. */
  tint: string;
  /** Feature color on the map. */
  color: string;
  kind: MarkerKind;
  defaultOn: boolean;
  blurb: string;
  /** Relative size of dot / ring markers. */
  pointScale: number;
  icon: string;
}

export const LAYERS = [
  {
    id: "roads",
    z: 50,
    label: "Roads",
    group: "data",
    accent: "#12866f",
    tint: "#e3f6f1",
    color: "#23938a",
    kind: "line",
    defaultOn: true,
    blurb: "Preview motorway and trunk corridors",
    pointScale: 1,
    icon: ICONS.roads,
  },
  {
    id: "pubs",
    z: 220,
    label: "Pubs",
    group: "data",
    accent: "#d99212",
    tint: "#fff3dc",
    color: "#f0a31c",
    kind: "dot",
    defaultOn: true,
    blurb: "Preview pub locations",
    pointScale: 1.15,
    icon: ICONS.pubs,
  },
  {
    id: "schools",
    z: 140,
    label: "Schools",
    group: "data",
    accent: "#6d5bd4",
    tint: "#eee9fb",
    color: "#7464d6",
    kind: "dot",
    defaultOn: true,
    blurb: "Preview schools",
    pointScale: 0.92,
    icon: ICONS.schools,
  },
  {
    id: "hospitals",
    z: 240,
    label: "Hospitals",
    group: "data",
    accent: "#e3534a",
    tint: "#fdeceb",
    color: "#e3534a",
    kind: "cross",
    defaultOn: true,
    blurb: "Preview hospitals",
    pointScale: 1,
    icon: ICONS.hospitals,
  },
  {
    id: "churches",
    z: 110,
    label: "Churches",
    group: "data",
    accent: "#7d62c8",
    tint: "#f3eefc",
    color: "#8d74d4",
    kind: "dot",
    defaultOn: true,
    blurb: "Preview churches",
    pointScale: 0.82,
    icon: ICONS.churches,
  },
  {
    id: "post-offices",
    z: 210,
    label: "Post offices",
    group: "data",
    accent: "#e25b52",
    tint: "#fdeeee",
    color: "#e25b52",
    kind: "ring",
    defaultOn: false,
    blurb: "Preview post offices",
    pointScale: 1,
    icon: ICONS.post,
  },
  {
    id: "mosques",
    z: 120,
    label: "Mosques",
    group: "data",
    accent: "#b0893e",
    tint: "#f8f1e2",
    color: "#c49a45",
    kind: "diamond",
    defaultOn: false,
    blurb: "Preview mosques",
    pointScale: 1,
    icon: ICONS.mosques,
  },
  {
    id: "population",
    z: 10,
    label: "Population",
    group: "data",
    accent: "#d79a2b",
    tint: "#fff4df",
    color: "#e2b15a",
    kind: "disc",
    defaultOn: false,
    blurb: "Preview population discs sized by settlement",
    pointScale: 1,
    icon: ICONS.population,
  },
  {
    id: "other-religious",
    z: 130,
    label: "Other religious",
    group: "data",
    accent: "#7d848f",
    tint: "#f1f2f4",
    color: "#8b919c",
    kind: "ring",
    defaultOn: false,
    blurb: "Preview other religious sites",
    pointScale: 0.95,
    icon: ICONS.religious,
  },
  {
    id: "census",
    z: 20,
    label: "Census",
    group: "data",
    accent: "#7e868f",
    tint: "#f0f1f3",
    color: "#9aa3ad",
    kind: "square",
    defaultOn: false,
    blurb: "Preview census markers",
    pointScale: 1,
    icon: ICONS.census,
  },
  {
    id: "petrol",
    z: 80,
    label: "Petrol stations",
    group: "data",
    accent: "#d4532b",
    tint: "#fdeee8",
    color: "#e15a32",
    kind: "dot",
    defaultOn: false,
    blurb: "OpenStreetMap fuel stations (ODbL)",
    pointScale: 0.95,
    icon: ICONS.petrol,
  },
  {
    id: "ev",
    z: 90,
    label: "EV charging",
    group: "data",
    accent: "#1c9a48",
    tint: "#e7f7ec",
    color: "#22a84f",
    kind: "dot",
    defaultOn: false,
    blurb: "OpenStreetMap charging stations (ODbL)",
    pointScale: 0.9,
    icon: ICONS.ev,
  },
  {
    id: "cemeteries",
    z: 100,
    label: "Cemeteries",
    group: "upcoming",
    accent: "#6d7480",
    tint: "#f1f2f4",
    color: "#7b8490",
    kind: "diamond",
    defaultOn: false,
    blurb: "Upcoming · preview cemeteries",
    pointScale: 1,
    icon: ICONS.cemeteries,
  },
  {
    id: "immigration",
    z: 180,
    label: "Immigration",
    group: "upcoming",
    accent: "#2b7fd4",
    tint: "#e8f2fc",
    color: "#3b8adf",
    kind: "square",
    defaultOn: false,
    blurb: "Upcoming · preview ports and airports",
    pointScale: 1,
    icon: ICONS.immigration,
  },
  {
    id: "crime",
    z: 190,
    label: "Crime",
    group: "upcoming",
    accent: "#c4364a",
    tint: "#fdecef",
    color: "#d14558",
    kind: "dot",
    defaultOn: false,
    blurb: "Upcoming · preview markers, not live crime data",
    pointScale: 1.05,
    icon: ICONS.crime,
  },
  {
    id: "health",
    z: 200,
    label: "Health",
    group: "upcoming",
    accent: "#d94872",
    tint: "#fdeef3",
    color: "#e25b84",
    kind: "cross",
    defaultOn: false,
    blurb: "Upcoming · preview health markers",
    pointScale: 1,
    icon: ICONS.health,
  },
  {
    id: "weather",
    z: 30,
    label: "Weather",
    group: "upcoming",
    accent: "#2f93c8",
    tint: "#e7f4fb",
    color: "#3aa0d4",
    kind: "dot",
    defaultOn: false,
    blurb: "Upcoming · preview weather stations",
    pointScale: 1.2,
    icon: ICONS.weather,
  },
  {
    id: "power",
    z: 70,
    label: "Power",
    group: "data",
    accent: "#d49216",
    tint: "#fff4e2",
    color: "#e0a322",
    kind: "square",
    defaultOn: false,
    blurb: "OpenStreetMap power plants (ODbL)",
    pointScale: 1,
    icon: ICONS.power,
  },
  {
    id: "wind",
    z: 60,
    label: "Wind turbines",
    group: "upcoming",
    accent: "#1497ab",
    tint: "#e5f6f8",
    color: "#1aa8bc",
    kind: "triangle",
    defaultOn: false,
    blurb: "Upcoming · preview wind areas",
    pointScale: 1,
    icon: ICONS.wind,
  },
  {
    id: "nuclear",
    z: 230,
    label: "Nuclear",
    group: "upcoming",
    accent: "#6e9418",
    tint: "#f1f7e4",
    color: "#7aa31a",
    kind: "ring",
    defaultOn: false,
    blurb: "Upcoming · preview nuclear sites",
    pointScale: 1.25,
    icon: ICONS.nuclear,
  },
  {
    id: "castles",
    z: 170,
    label: "Castles",
    group: "upcoming",
    accent: "#9a6232",
    tint: "#f8efe8",
    color: "#a56b38",
    kind: "square",
    defaultOn: false,
    blurb: "Upcoming · preview castles",
    pointScale: 1,
    icon: ICONS.castles,
  },
  {
    id: "historic",
    z: 150,
    label: "Historic",
    group: "upcoming",
    accent: "#b26a2a",
    tint: "#f8f0e6",
    color: "#c47a34",
    kind: "diamond",
    defaultOn: false,
    blurb: "Upcoming · preview historic sites",
    pointScale: 1,
    icon: ICONS.historic,
  },
  {
    id: "legends",
    z: 160,
    label: "Legends",
    group: "upcoming",
    accent: "#7a4ec4",
    tint: "#f3ecfb",
    color: "#8a5fd0",
    kind: "dot",
    defaultOn: false,
    blurb: "Upcoming · preview legend sites",
    pointScale: 1.1,
    icon: ICONS.legends,
  },
  {
    id: "mountains",
    z: 40,
    label: "Mountains",
    group: "upcoming",
    accent: "#6a6258",
    tint: "#f3f1ef",
    color: "#7a7268",
    kind: "triangle",
    defaultOn: false,
    blurb: "Upcoming · preview summits",
    pointScale: 1,
    icon: ICONS.mountains,
  },
] as const satisfies readonly LayerDef[];

export type LayerId = (typeof LAYERS)[number]["id"];

export function isLayerId(value: unknown): value is LayerId {
  return typeof value === "string" && LAYERS.some((layer) => layer.id === value);
}

export function layerById(id: string): LayerDef {
  const layer = LAYERS.find((item) => item.id === id);
  if (!layer) throw new Error(`Unknown layer ${id}`);
  return layer;
}
