import { ICONS } from "./icons";

export type MarkerKind =
  | "line"
  | "dot"
  | "disc"
  | "ring"
  | "cross"
  | "diamond"
  | "square"
  | "triangle";

export interface LayerDef {
  readonly id: string;
  readonly z: number;
  label: string;
  group: "data" | "upcoming";
  /** Chip icon color. */
  accent: string;
  /** Active chip background. */
  tint: string;
  /** Feature color on the map. */
  color: string;
  kind: MarkerKind;
  defaultOn: boolean;
  blurb: string;
  /** Relative size of dot / ring markers. */
  pointScale: number;
  icon: string;
}

export const LAYERS = [
  {
    id: "roads",
    z: 50,
    label: "Roads",
    group: "data",
    accent: "#12866f",
    tint: "#e3f6f1",
    color: "#23938a",
    kind: "line",
    defaultOn: true,
    blurb: "Preview motorway and trunk corridors",
    pointScale: 1,
    icon: ICONS.roads,
  },
  {
    id: "pubs",
    z: 220,
    label: "Pubs",
    group: "data",
    accent: "#d99212",
    tint: "#fff3dc",
    color: "#f0a31c",
    kind: "dot",
    defaultOn: true,
    blurb: "Preview pub locations",
    pointScale: 1.15,
    icon: ICONS.pubs,
  },
  {
    id: "schools",
    z: 140,
    label: "Schools",
    group: "data",
    accent: "#6d5bd4",
    tint: "#eee9fb",
    color: "#7464d6",
    kind: "dot",
    defaultOn: true,
    blurb: "Preview schools",
    pointScale: 0.92,
    icon: ICONS.schools,
  },
  {
    id: "libraries",
    z: 145,
    label: "Libraries",
    group: "data",
    accent: "#3d6f9e",
    tint: "#e8f0f7",
    color: "#4680b0",
    kind: "dot",
    defaultOn: false,
    blurb: "OpenStreetMap libraries (ODbL)",
    pointScale: 0.95,
    icon: ICONS.libraries,
  },
  {
    id: "universities",
    z: 148,
    label: "Universities",
    group: "data",
    accent: "#5a4fb0",
    tint: "#eeebf8",
    color: "#6558c0",
    kind: "square",
    defaultOn: false,
    blurb: "OpenStreetMap universities (ODbL)",
    pointScale: 1,
    icon: ICONS.universities,
  },
  {
    id: "museums",
    z: 155,
    label: "Museums",
    group: "data",
    accent: "#8b5a2b",
    tint: "#f7f0e8",
    color: "#9a6633",
    kind: "diamond",
    defaultOn: false,
    blurb: "OpenStreetMap museums (ODbL)",
    pointScale: 1,
    icon: ICONS.museums,
  },
  {
    id: "railway-stations",
    z: 158,
    label: "Railway stations",
    group: "data",
    accent: "#3a5f8a",
    tint: "#e8eef5",
    color: "#4470a0",
    kind: "square",
    defaultOn: false,
    blurb: "OpenStreetMap railway stations (ODbL)",
    pointScale: 0.95,
    icon: ICONS["railway-stations"],
  },
  {
    id: "aerodromes",
    z: 162,
    label: "Aerodromes",
    group: "data",
    accent: "#2f6f7a",
    tint: "#e6f2f4",
    color: "#37848f",
    kind: "diamond",
    defaultOn: false,
    blurb: "OpenStreetMap aerodromes (ODbL)",
    pointScale: 1,
    icon: ICONS.aerodromes,
  },
  {
    id: "ferry-terminals",
    z: 164,
    label: "Ferry terminals",
    group: "data",
    accent: "#1f6f9c",
    tint: "#e5f1f8",
    color: "#2780b0",
    kind: "triangle",
    defaultOn: false,
    blurb: "OpenStreetMap ferry terminals (ODbL)",
    pointScale: 1,
    icon: ICONS["ferry-terminals"],
  },
  {
    id: "marinas",
    z: 166,
    label: "Marinas",
    group: "data",
    accent: "#0f7a7a",
    tint: "#e4f4f4",
    color: "#168888",
    kind: "diamond",
    defaultOn: false,
    blurb: "OpenStreetMap marinas (ODbL)",
    pointScale: 1,
    icon: ICONS.marinas,
  },
  {
    id: "zoos",
    z: 168,
    label: "Zoos",
    group: "data",
    accent: "#2f7a3a",
    tint: "#e8f4ea",
    color: "#378a42",
    kind: "square",
    defaultOn: false,
    blurb: "OpenStreetMap zoos (ODbL)",
    pointScale: 1,
    icon: ICONS.zoos,
  },
  {
    id: "theatres",
    z: 170,
    label: "Theatres",
    group: "data",
    accent: "#7a3a8a",
    tint: "#f3eaf6",
    color: "#8a429a",
    kind: "triangle",
    defaultOn: false,
    blurb: "OpenStreetMap theatres (ODbL)",
    pointScale: 1,
    icon: ICONS.theatres,
  },
  {
    id: "battlefields",
    z: 172,
    label: "Battlefields",
    group: "data",
    accent: "#6b4a2a",
    tint: "#f3ebe3",
    color: "#7a5533",
    kind: "diamond",
    defaultOn: false,
    blurb: "OpenStreetMap battlefields (ODbL)",
    pointScale: 1,
    icon: ICONS.battlefields,
  },
  {
    id: "cinemas",
    z: 174,
    label: "Cinemas",
    group: "data",
    accent: "#4a3a8a",
    tint: "#eeebf6",
    color: "#5542a0",
    kind: "square",
    defaultOn: false,
    blurb: "OpenStreetMap cinemas (ODbL)",
    pointScale: 1,
    icon: ICONS.cinemas,
  },
  {
    id: "stadiums",
    z: 176,
    label: "Stadiums",
    group: "data",
    accent: "#2a6b4a",
    tint: "#e6f3ec",
    color: "#337a55",
    kind: "triangle",
    defaultOn: false,
    blurb: "OpenStreetMap stadiums (ODbL)",
    pointScale: 1,
    icon: ICONS.stadiums,
  },
  {
    id: "theme-parks",
    z: 178,
    label: "Theme parks",
    group: "data",
    accent: "#c45a2a",
    tint: "#fceee6",
    color: "#d46833",
    kind: "diamond",
    defaultOn: false,
    blurb: "OpenStreetMap theme parks (ODbL)",
    pointScale: 1,
    icon: ICONS["theme-parks"],
  },
  {
    id: "viewpoints",
    z: 180,
    label: "Viewpoints",
    group: "data",
    accent: "#1a7a8c",
    tint: "#e6f4f6",
    color: "#2290a3",
    kind: "ring",
    defaultOn: false,
    blurb: "OpenStreetMap viewpoints (ODbL)",
    pointScale: 1,
    icon: ICONS.viewpoints,
  },
  {
    id: "arts-centres",
    z: 182,
    label: "Arts centres",
    group: "data",
    accent: "#8a3a6a",
    tint: "#f6eaf2",
    color: "#9a4278",
    kind: "square",
    defaultOn: false,
    blurb: "OpenStreetMap arts centres (ODbL)",
    pointScale: 1,
    icon: ICONS["arts-centres"],
  },
  {
    id: "aquariums",
    z: 184,
    label: "Aquariums",
    group: "data",
    accent: "#1a6a8c",
    tint: "#e6f2f6",
    color: "#2280a3",
    kind: "diamond",
    defaultOn: false,
    blurb: "OpenStreetMap aquariums (ODbL)",
    pointScale: 1,
    icon: ICONS.aquariums,
  },
  {
    id: "piers",
    z: 186,
    label: "Piers",
    group: "data",
    accent: "#3a6a8a",
    tint: "#e8f0f5",
    color: "#4a7a9a",
    kind: "square",
    defaultOn: false,
    blurb: "OpenStreetMap named piers (ODbL)",
    pointScale: 1,
    icon: ICONS.piers,
  },
  {
    id: "ruins",
    z: 188,
    label: "Ruins",
    group: "data",
    accent: "#6a5a4a",
    tint: "#f2efe9",
    color: "#7a6a55",
    kind: "diamond",
    defaultOn: false,
    blurb: "OpenStreetMap named ruins (ODbL)",
    pointScale: 1,
    icon: ICONS.ruins,
  },
  {
    id: "golf-courses",
    z: 190,
    label: "Golf courses",
    group: "data",
    accent: "#3d8a4a",
    tint: "#e8f5ea",
    color: "#4a9a58",
    kind: "square",
    defaultOn: false,
    blurb: "OpenStreetMap golf courses (ODbL)",
    pointScale: 1,
    icon: ICONS["golf-courses"],
  },
  {
    id: "galleries",
    z: 192,
    label: "Galleries",
    group: "data",
    accent: "#a84d7a",
    tint: "#f8ebf1",
    color: "#b85a88",
    kind: "diamond",
    defaultOn: false,
    blurb: "OpenStreetMap galleries (ODbL)",
    pointScale: 1,
    icon: ICONS.galleries,
  },
  {
    id: "marketplaces",
    z: 194,
    label: "Marketplaces",
    group: "data",
    accent: "#c4782a",
    tint: "#faf0e4",
    color: "#d4882e",
    kind: "square",
    defaultOn: false,
    blurb: "OpenStreetMap marketplaces (ODbL)",
    pointScale: 1,
    icon: ICONS.marketplaces,
  },
  {
    id: "nature-reserves",
    z: 196,
    label: "Nature reserves",
    group: "data",
    accent: "#2f7a3a",
    tint: "#e8f5ea",
    color: "#378a42",
    kind: "diamond",
    defaultOn: false,
    blurb: "OpenStreetMap nature reserves (ODbL)",
    pointScale: 1,
    icon: ICONS["nature-reserves"],
  },
  {
    id: "hospitals",
    z: 240,
    label: "Hospitals",
    group: "data",
    accent: "#e3534a",
    tint: "#fdeceb",
    color: "#e3534a",
    kind: "cross",
    defaultOn: false,
    blurb: "OpenStreetMap hospitals (ODbL)",
    pointScale: 1,
    icon: ICONS.hospitals,
  },
  {
    id: "fire-stations",
    z: 235,
    label: "Fire stations",
    group: "data",
    accent: "#c4402a",
    tint: "#fdeae6",
    color: "#d14933",
    kind: "square",
    defaultOn: false,
    blurb: "OpenStreetMap fire stations (ODbL)",
    pointScale: 1,
    icon: ICONS["fire-stations"],
  },
  {
    id: "police",
    z: 238,
    label: "Police",
    group: "data",
    accent: "#2b5aa8",
    tint: "#e8eef8",
    color: "#3468bc",
    kind: "diamond",
    defaultOn: false,
    blurb: "OpenStreetMap police stations (ODbL)",
    pointScale: 1,
    icon: ICONS.police,
  },
  {
    id: "churches",
    z: 110,
    label: "Churches",
    group: "data",
    accent: "#7d62c8",
    tint: "#f3eefc",
    color: "#8d74d4",
    kind: "dot",
    defaultOn: true,
    blurb: "Preview churches",
    pointScale: 0.82,
    icon: ICONS.churches,
  },
  {
    id: "post-offices",
    z: 210,
    label: "Post offices",
    group: "data",
    accent: "#e25b52",
    tint: "#fdeeee",
    color: "#e25b52",
    kind: "ring",
    defaultOn: false,
    blurb: "Preview post offices",
    pointScale: 1,
    icon: ICONS.post,
  },
  {
    id: "mosques",
    z: 120,
    label: "Mosques",
    group: "data",
    accent: "#b0893e",
    tint: "#f8f1e2",
    color: "#c49a45",
    kind: "diamond",
    defaultOn: false,
    blurb: "Preview mosques",
    pointScale: 1,
    icon: ICONS.mosques,
  },
  {
    id: "population",
    z: 10,
    label: "Population",
    group: "data",
    accent: "#d79a2b",
    tint: "#fff4df",
    color: "#e2b15a",
    kind: "disc",
    defaultOn: false,
    blurb: "Preview population discs sized by settlement",
    pointScale: 1,
    icon: ICONS.population,
  },
  {
    id: "other-religious",
    z: 130,
    label: "Other religious",
    group: "data",
    accent: "#7d848f",
    tint: "#f1f2f4",
    color: "#8b919c",
    kind: "ring",
    defaultOn: false,
    blurb: "Preview other religious sites",
    pointScale: 0.95,
    icon: ICONS.religious,
  },
  {
    id: "census",
    z: 20,
    label: "Census",
    group: "data",
    accent: "#7e868f",
    tint: "#f0f1f3",
    color: "#9aa3ad",
    kind: "square",
    defaultOn: false,
    blurb: "Preview census markers",
    pointScale: 1,
    icon: ICONS.census,
  },
  {
    id: "petrol",
    z: 80,
    label: "Petrol stations",
    group: "data",
    accent: "#d4532b",
    tint: "#fdeee8",
    color: "#e15a32",
    kind: "dot",
    defaultOn: false,
    blurb: "OpenStreetMap fuel stations (ODbL)",
    pointScale: 0.95,
    icon: ICONS.petrol,
  },
  {
    id: "ev",
    z: 90,
    label: "EV charging",
    group: "data",
    accent: "#1c9a48",
    tint: "#e7f7ec",
    color: "#22a84f",
    kind: "dot",
    defaultOn: false,
    blurb: "OpenStreetMap charging stations (ODbL)",
    pointScale: 0.9,
    icon: ICONS.ev,
  },
  {
    id: "cemeteries",
    z: 100,
    label: "Cemeteries",
    group: "upcoming",
    accent: "#6d7480",
    tint: "#f1f2f4",
    color: "#7b8490",
    kind: "diamond",
    defaultOn: false,
    blurb: "Upcoming · preview cemeteries",
    pointScale: 1,
    icon: ICONS.cemeteries,
  },
  {
    id: "immigration",
    z: 180,
    label: "Immigration",
    group: "upcoming",
    accent: "#2b7fd4",
    tint: "#e8f2fc",
    color: "#3b8adf",
    kind: "square",
    defaultOn: false,
    blurb: "Upcoming · preview ports and airports",
    pointScale: 1,
    icon: ICONS.immigration,
  },
  {
    id: "crime",
    z: 190,
    label: "Crime",
    group: "upcoming",
    accent: "#c4364a",
    tint: "#fdecef",
    color: "#d14558",
    kind: "dot",
    defaultOn: false,
    blurb: "Upcoming · preview markers, not live crime data",
    pointScale: 1.05,
    icon: ICONS.crime,
  },
  {
    id: "health",
    z: 200,
    label: "Health",
    group: "upcoming",
    accent: "#d94872",
    tint: "#fdeef3",
    color: "#e25b84",
    kind: "cross",
    defaultOn: false,
    blurb: "Upcoming · preview health markers",
    pointScale: 1,
    icon: ICONS.health,
  },
  {
    id: "weather",
    z: 30,
    label: "Weather",
    group: "upcoming",
    accent: "#2f93c8",
    tint: "#e7f4fb",
    color: "#3aa0d4",
    kind: "dot",
    defaultOn: false,
    blurb: "Upcoming · preview weather stations",
    pointScale: 1.2,
    icon: ICONS.weather,
  },
  {
    id: "power",
    z: 70,
    label: "Power",
    group: "data",
    accent: "#d49216",
    tint: "#fff4e2",
    color: "#e0a322",
    kind: "square",
    defaultOn: false,
    blurb: "OpenStreetMap power plants (ODbL)",
    pointScale: 1,
    icon: ICONS.power,
  },
  {
    id: "wind",
    z: 60,
    label: "Wind turbines",
    group: "upcoming",
    accent: "#1497ab",
    tint: "#e5f6f8",
    color: "#1aa8bc",
    kind: "triangle",
    defaultOn: false,
    blurb: "Upcoming · preview wind areas",
    pointScale: 1,
    icon: ICONS.wind,
  },
  {
    id: "nuclear",
    z: 230,
    label: "Nuclear",
    group: "upcoming",
    accent: "#6e9418",
    tint: "#f1f7e4",
    color: "#7aa31a",
    kind: "ring",
    defaultOn: false,
    blurb: "Upcoming · preview nuclear sites",
    pointScale: 1.25,
    icon: ICONS.nuclear,
  },
  {
    id: "castles",
    z: 170,
    label: "Castles",
    group: "data",
    accent: "#9a6232",
    tint: "#f8efe8",
    color: "#a56b38",
    kind: "square",
    defaultOn: false,
    blurb: "OpenStreetMap castles (ODbL)",
    pointScale: 1,
    icon: ICONS.castles,
  },
  {
    id: "historic",
    z: 150,
    label: "Historic",
    group: "upcoming",
    accent: "#b26a2a",
    tint: "#f8f0e6",
    color: "#c47a34",
    kind: "diamond",
    defaultOn: false,
    blurb: "Upcoming · preview historic sites",
    pointScale: 1,
    icon: ICONS.historic,
  },
  {
    id: "legends",
    z: 160,
    label: "Legends",
    group: "upcoming",
    accent: "#7a4ec4",
    tint: "#f3ecfb",
    color: "#8a5fd0",
    kind: "dot",
    defaultOn: false,
    blurb: "Upcoming · preview legend sites",
    pointScale: 1.1,
    icon: ICONS.legends,
  },
  {
    id: "mountains",
    z: 40,
    label: "Mountains",
    group: "upcoming",
    accent: "#6a6258",
    tint: "#f3f1ef",
    color: "#7a7268",
    kind: "triangle",
    defaultOn: false,
    blurb: "Upcoming · preview summits",
    pointScale: 1,
    icon: ICONS.mountains,
  },
] as const satisfies readonly LayerDef[];

export type LayerId = (typeof LAYERS)[number]["id"];

export function isLayerId(value: unknown): value is LayerId {
  return typeof value === "string" && LAYERS.some((layer) => layer.id === value);
}

export function layerById(id: string): LayerDef {
  const layer = LAYERS.find((item) => item.id === id);
  if (!layer) throw new Error(`Unknown layer ${id}`);
  return layer;
}
